name: data
on:
  schedule:
    - cron: 1 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denolib/setup-deno@v2
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv
          downloaded_filename: covid_stats.csv
